# Generated by Django 2.2.4 on 2019-10-15 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_marca', models.CharField(help_text='Descrição da marca', max_length=100, verbose_name='Marca')),
            ],
            options={
                'verbose_name_plural': '01 - Cadastro de marcas',
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(help_text='Descrição da unidade de medida', max_length=50, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': '02 - Cadastro de unidades de medida',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_produto', models.CharField(help_text='Descrição do produto', max_length=150, verbose_name='Descrição')),
                ('num_serie', models.CharField(help_text='Número de série', max_length=150, verbose_name='Número de série')),
                ('descricao_marca', models.ForeignKey(help_text='Marca', on_delete=django.db.models.deletion.CASCADE, to='produtos.Marca', verbose_name='Marca')),
                ('unidade', models.ForeignKey(help_text='Unidade', on_delete=django.db.models.deletion.CASCADE, to='produtos.UnidadeMedida', verbose_name='Unidade')),
            ],
            options={
                'verbose_name_plural': '03 - Cadastro de produtos',
            },
        ),
    ]
