# Generated by Django 2.2.4 on 2019-10-15 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_auto_20191015_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='descricao_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='descricao_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do fornecedor'),
        ),
    ]
