# Generated by Django 2.2.4 on 2019-10-16 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0004_auto_20191016_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='nome',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='requisitantes.Requisitante', verbose_name='Nome do Destinatário'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='num_serie_produto',
            field=models.CharField(blank=True, max_length=150, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='setor',
            field=models.CharField(blank=True, max_length=150, verbose_name='Setor do Destinatário'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacoes.Tipo', verbose_name='Tipo de Movimentação'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tombo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Número do Tombo'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidade_medida', to='produtos.Produto', verbose_name='Unidade de Medida'),
        ),
    ]
