# Generated by Django 2.2.4 on 2019-10-16 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0005_auto_20191016_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidade_medida', to='produtos.UnidadeMedida', verbose_name='Unidade de Medida'),
        ),
    ]
