# Generated by Django 2.2.4 on 2019-10-16 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0007_auto_20191016_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='nome',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='requisitantes.Requisitante', verbose_name='Nome do Requisitante'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.UnidadeMedida', verbose_name='Unidade de Medida'),
        ),
    ]
