# Generated by Django 2.2.4 on 2019-10-16 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0008_auto_20191016_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='tombo',
        ),
    ]
