# Generated by Django 2.2.4 on 2019-10-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('setor', models.CharField(max_length=200, verbose_name='Setor')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.CharField(max_length=50, verbose_name='e-mail')),
            ],
            options={
                'verbose_name_plural': '01 - Cadastro de Requisitantes',
            },
        ),
    ]
